name: Build on PR

on:
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}

jobs:
  run:
    name: Build on PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install

      - uses: DamianReeves/write-file-action@v1.3
        with:
          path: .env
          contents: ${{ secrets.ENV }}
          write-mode: overwrite

      - run: npm run lint
      - run: npm test
      - run: npm run build
